#Requires -Version 5.1
<#
.SYNOPSIS
  PentestIQ installer for Windows — Docker SaaS stack or a local Python run.

.DESCRIPTION
  Docker path (recommended, full parity with macOS/Linux install.sh):
    powershell -ExecutionPolicy Bypass -File .\install.ps1 -Docker
    powershell -ExecutionPolicy Bypass -File .\install.ps1 -Docker -Update
    powershell -ExecutionPolicy Bypass -File .\install.ps1 -Docker -Down
    powershell -ExecutionPolicy Bypass -File .\install.ps1 -Docker -Ai      # deploy WITH local AI
    powershell -ExecutionPolicy Bypass -File .\install.ps1 -Docker -NoAi    # skip the AI prompt

  Python path (no Docker; runs the API from a virtualenv):
    powershell -ExecutionPolicy Bypass -File .\install.ps1
    powershell -ExecutionPolicy Bypass -File .\install.ps1 -Port 9090

.NOTES
  The Docker image is built from the same Debian base on every OS, so the
  scanning engine (crawler, native OWASP checks, injection fuzzer, OAST) plus
  the bundled tools (nmap, headless chromium for SPA crawl, nuclei) behave
  identically on Windows, macOS and Linux.
#>
[CmdletBinding()]
param(
  [int]$Port = 8080,
  [switch]$Docker,
  [switch]$Update,
  [switch]$Down,
  [switch]$Ai,
  [switch]$NoAi,
  [switch]$NoServe,
  [switch]$All,
  [switch]$Help
)

$ErrorActionPreference = "Stop"
$RepoDir     = Split-Path -Parent $MyInvocation.MyCommand.Path
$ComposeFile = Join-Path $RepoDir "deploy\docker-compose.yml"
$EnvFile     = Join-Path $RepoDir "deploy\.env"
$AiModel     = if ($env:PENTESTIQ_AI_MODEL) { $env:PENTESTIQ_AI_MODEL } else { "qwen2.5:7b-instruct" }
$script:AiOn = $false

function Info($m) { Write-Host "[PentestIQ] $m" -ForegroundColor Cyan }
function Ok($m)   { Write-Host "[ ok ] $m"     -ForegroundColor Green }
function Warn($m) { Write-Host "[warn] $m"     -ForegroundColor Yellow }
function Die($m)  { Write-Host "[fail] $m"     -ForegroundColor Red; exit 1 }

if ($Help) { Get-Help $MyInvocation.MyCommand.Path -Detailed; exit 0 }

Write-Host ""
Write-Host "  PentestIQ - Windows installer" -ForegroundColor Blue
Write-Host ""

function New-Secret([int]$n = 48) {
  -join ((48..57)+(97..122) | Get-Random -Count $n | ForEach-Object {[char]$_})
}

# Resolve the compose command: v2 "docker compose" (Docker Desktop) or v1 "docker-compose".
function Get-Compose {
  try { docker compose version *> $null; if ($LASTEXITCODE -eq 0) { return @("docker","compose") } } catch {}
  if (Get-Command docker-compose -ErrorAction SilentlyContinue) { return @("docker-compose") }
  Die "Docker Compose not found. Install/enable Docker Desktop (which bundles Compose v2)."
}

function Invoke-Compose([string[]]$Rest) {
  $dc = Get-Compose
  $args = @()
  if ($dc.Count -gt 1) { $args += $dc[1] }   # the "compose" subcommand for v2
  $args += @("--env-file", $EnvFile, "-f", $ComposeFile) + $Rest
  & $dc[0] @args
}

function Write-Env {
  $dir = Split-Path -Parent $EnvFile
  if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  if (Test-Path $EnvFile) { Ok "Reusing existing secrets ($EnvFile)."; return }
  Info "Generating secrets -> $EnvFile"
  "# PentestIQ deployment secrets - generated by install.ps1. Keep private; do not commit.`n" +
  "MOBSF_API_KEY=$(New-Secret 32)`n" +
  "PENTESTIQ_SECRET_KEY=$(New-Secret 48)`n" +
  "PENTESTIQ_PORT=$Port`n" +
  ("PENTESTIQ_AI=" + $(if ($script:AiOn) {"1"} else {"0"}) + "`n") +
  "OLLAMA_URL=http://ollama:11434`n" +
  "PENTESTIQ_AI_MODEL=$AiModel" | Set-Content -Path $EnvFile -Encoding ASCII
  Ok "Secrets generated."
}

function Ask-Ai {
  if ($Ai)   { $script:AiOn = $true;  return }
  if ($NoAi) { $script:AiOn = $false; return }
  if ((Test-Path $EnvFile) -and (Select-String -Path $EnvFile -Pattern '^PENTESTIQ_AI=1' -Quiet)) { $script:AiOn = $true; return }
  Write-Host ""
  Info "Optional AI layer (local, self-hosted Ollama model)."
  Write-Host "  It adds AI-written findings, attack-chain correlation, a false-positive" -ForegroundColor DarkGray
  Write-Host "  verifier, an in-console copilot, and a self-learning confidence model." -ForegroundColor DarkGray
  Write-Host "  Requires a high-spec workstation/lab: 8+ CPU cores, 16 GB+ RAM (GPU optional)," -ForegroundColor Yellow
  Write-Host "  plus a ~5 GB one-time model download. Everything runs locally." -ForegroundColor Yellow
  $ans = Read-Host "Do you want to install / integrate AI? [y/N]"
  $script:AiOn = ($ans -match '^[Yy]')
}

function Set-AiEnv {
  if (-not (Test-Path $EnvFile)) { return }
  $val = if ($script:AiOn) {"1"} else {"0"}
  $c = Get-Content $EnvFile
  if ($c -match '^PENTESTIQ_AI=') {
    ($c -replace '^PENTESTIQ_AI=.*', "PENTESTIQ_AI=$val") | Set-Content -Path $EnvFile -Encoding ASCII
  } else {
    Add-Content -Path $EnvFile -Value "PENTESTIQ_AI=$val`nOLLAMA_URL=http://ollama:11434`nPENTESTIQ_AI_MODEL=$AiModel"
  }
}

function Wait-Ollama {
  Info "Waiting for the local AI service (Ollama) to become ready..."
  for ($i = 0; $i -lt 40; $i++) {
    try { $r = Invoke-WebRequest -UseBasicParsing -TimeoutSec 4 "http://localhost:11434/api/tags"
      if ($r.StatusCode -eq 200) { Ok "Ollama is up."; return $true } } catch {}
    Start-Sleep -Seconds 3
  }
  Warn "Ollama not ready yet - pull later with: docker exec -it pentestiq-ollama ollama pull $AiModel"
  return $false
}

function Pull-Model {
  Info "Pulling the AI model '$AiModel' (~5 GB, one-time)... this can take a while."
  docker exec pentestiq-ollama ollama pull $AiModel
  if ($LASTEXITCODE -eq 0) { Ok "AI model ready: $AiModel" }
  else { Warn "Model pull failed - retry: docker exec -it pentestiq-ollama ollama pull $AiModel" }
}

function Deploy-Stack {
  if (-not (Test-Path $ComposeFile)) { Die "compose file not found: $ComposeFile (run this from the PentestIQ repo)." }
  Info "Building and starting the stack (this can take a few minutes on first run)..."
  # Pre-pull the base image via the daemon, then build with the LEGACY builder.
  # BuildKit uses a separate DNS resolver that some corporate/VM DNS setups can't
  # use to reach the registry (auth.docker.io) even when the daemon resolves fine;
  # the legacy builder shares the daemon's networking. Same workaround as install.sh.
  try { docker pull python:3.11-slim *> $null } catch {}
  $env:DOCKER_BUILDKIT = "0"
  $env:COMPOSE_DOCKER_CLI_BUILD = "0"
  if ($script:AiOn) { Info "AI layer enabled - the Ollama service will start too."; Invoke-Compose @("--profile","ai","up","-d","--build") }
  else { Invoke-Compose @("up", "-d", "--build") }
  if ($LASTEXITCODE -ne 0) { Die "Build/deploy failed. See the output above." }
  Ok "Containers started."
}

function Wait-Healthy {
  Info "Waiting for the PentestIQ API to become healthy..."
  for ($i = 0; $i -lt 40; $i++) {
    try {
      $r = Invoke-WebRequest -UseBasicParsing -TimeoutSec 4 "http://localhost:$Port/health"
      if ($r.StatusCode -eq 200) { Ok "PentestIQ is up."; return }
    } catch {}
    Start-Sleep -Seconds 3
  }
  Warn "API health check timed out - it may still be starting. Check: docker compose -f `"$ComposeFile`" logs -f pentestiq"
}

function Show-Summary {
  $ip = "localhost"
  try {
    $a = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
         Where-Object { $_.IPAddress -notlike "127.*" -and $_.IPAddress -notlike "169.254.*" } |
         Select-Object -First 1
    if ($a) { $ip = $a.IPAddress }
  } catch {}
  Write-Host ""
  Write-Host "============================================================" -ForegroundColor Green
  Write-Host "  PentestIQ is deployed." -ForegroundColor Green
  Write-Host "============================================================" -ForegroundColor Green
  Write-Host "  Web console : http://localhost:$Port   (or http://$ip`:$Port)"
  Write-Host "  API docs    : http://localhost:$Port/docs"
  Write-Host "  MobSF       : http://localhost:8000  (mobile analysis engine)"
  if ($script:AiOn) { Write-Host "  AI layer    : enabled - local model $AiModel via Ollama (http://localhost:11434)" -ForegroundColor Green }
  else { Write-Host "  AI layer    : disabled (re-run with -Docker -Ai to enable)" -ForegroundColor DarkGray }
  Write-Host ""
  Write-Host "  Next steps:"
  Write-Host "    1) Open the console and sign in with pentestiq / p3nt3st!q (change the password after first login)."
  Write-Host "    2) Create a scan from New scan, or upload an app / API spec / Burp XML, then Run scan."
  Write-Host ""
  Write-Host "  Manage:"
  Write-Host "    logs   : docker compose --env-file `"$EnvFile`" -f `"$ComposeFile`" logs -f"
  Write-Host "    stop   : powershell -ExecutionPolicy Bypass -File .\install.ps1 -Docker -Down"
  Write-Host "    secrets: $EnvFile"
  Write-Host "============================================================" -ForegroundColor Green
  Write-Host ""
}

# --------------------------------------------------------------- Docker path
if ($Docker -or $Update -or $Down) {
  if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Die "Docker not found. Install Docker Desktop (https://www.docker.com/products/docker-desktop), start it, then re-run with -Docker."
  }
  try { docker info *> $null } catch { Die "Docker is installed but not running - start Docker Desktop and re-run." }

  if ($Down) {
    if (-not (Test-Path $EnvFile)) { "MOBSF_API_KEY=x`nPENTESTIQ_SECRET_KEY=x" | Set-Content -Path $EnvFile -Encoding ASCII }
    Info "Stopping the stack..."
    Invoke-Compose @("down")
    Ok "Stopped."
    exit 0
  }

  if ($Update) { Info "Update mode: rebuilding and redeploying (git pull yourself first)." }

  Ask-Ai
  Write-Env
  Set-AiEnv
  Deploy-Stack
  Wait-Healthy
  if ($script:AiOn) { if (Wait-Ollama) { Pull-Model } }
  Show-Summary
  exit 0
}

# --------------------------------------------------------------- Python path
# Supported for the local (venv) path: 3.10 - 3.12. Newer (3.13/3.14) often has
# no prebuilt wheels for compiled deps (pydantic-core, lxml, pillow, scipy),
# so pip tries to BUILD them from source and hangs on a box without a toolchain.
$MaxMinor = 12
function Get-PyInfo($exe, $pre) {
  $cmd = Get-Command $exe -ErrorAction SilentlyContinue
  if (-not $cmd) { return $null }
  if ($cmd.Source -and $cmd.Source -like "*\WindowsApps\*") { return $null }  # Store alias stub
  try { $out = (& $cmd.Source @pre "--version" 2>&1 | Out-String) } catch { return $null }
  if ($out -match "Python\s+(\d+)\.(\d+)") {
    $maj = [int]$Matches[1]; $min = [int]$Matches[2]
    if ($maj -eq 3 -and $min -ge 10) {
      $supported = ($min -le $MaxMinor)
      return [pscustomobject]@{ Exe = $cmd.Source; Pre = $pre; Ver = "$maj.$min"; Min = $min; Supported = $supported }
    }
  }
  return $null
}

$Py = $null; $TooNew = $null
# Prefer an explicitly supported interpreter (3.12 -> 3.11 -> 3.10) even when a
# newer one is also installed, then fall back to generic launchers.
$candidates = @(
  ,@("py", @("-3.12")), ,@("py", @("-3.11")), ,@("py", @("-3.10")),
  ,@("py", @("-3")),    ,@("python3", @()),    ,@("python", @())
)
foreach ($c in $candidates) {
  $info = Get-PyInfo $c[0] $c[1]
  if ($info) {
    if ($info.Supported) { $Py = $info; break }
    elseif (-not $TooNew) { $TooNew = $info }
  }
}

if (-not $Py) {
  if ($TooNew) {
    Warn "Python $($TooNew.Ver) is newer than PentestIQ's supported range (3.10-3.12)."
    Warn "Its compiled dependencies have no prebuilt wheels yet, so pip would try to build them from source (this is the 'stuck installing' hang)."
  } else {
    Warn "Python 3.10-3.12 was not found. (The 'python' Windows may offer is a Microsoft Store placeholder.)"
  }
  if (Get-Command winget -ErrorAction SilentlyContinue) {
    Info "Installing Python 3.12 via winget..."
    try {
      winget install --id Python.Python.3.12 -e --source winget --accept-package-agreements --accept-source-agreements
      Write-Host ""
      Warn "Python 3.12 installed. Close this window, open a NEW PowerShell, and run install.ps1 again (it will now prefer 3.12)."
      exit 0
    } catch {
      Die "Automatic install failed. Get Python 3.12 from https://python.org (tick 'Add python.exe to PATH'), then re-run — or use -Docker with Docker Desktop."
    }
  }
  Die "Install Python 3.12 from https://python.org (tick 'Add python.exe to PATH') and re-run, or use -Docker with Docker Desktop."
}
Ok "Python $($Py.Ver) detected."

$venv = Join-Path $RepoDir ".venv"
if (-not (Test-Path $venv)) {
  Info "Creating virtual environment (.venv)..."
  & $Py.Exe @($Py.Pre) -m venv "$venv"
}
$vpy = Join-Path $venv "Scripts\python.exe"
if (-not (Test-Path $vpy)) { Die "venv creation failed (no $vpy)." }

Info "Installing PentestIQ and dependencies (this may take a minute)..."
& $vpy -m pip install --upgrade pip --quiet
$extras = if ($All) { ".[all]" } else { ".[api,reports]" }
# --prefer-binary: use prebuilt wheels rather than compiling from source, so a
# missing toolchain fails fast with a clear error instead of hanging for hours.
& $vpy -m pip install --prefer-binary $extras
if ($LASTEXITCODE -ne 0) {
  Die "Dependency install failed. Most often this is an unsupported Python (use 3.10-3.12) or a package with no wheel for your platform. Try -Docker (Docker Desktop), or reinstall with Python 3.12."
}
Ok "PentestIQ installed."

$pentestiq = Join-Path $venv "Scripts\pentestiq.exe"
& $pentestiq version

if ($NoServe) {
  Write-Host ""
  Info "Skipping server start (-NoServe). To run later:  `"$pentestiq`" serve --host 0.0.0.0 --port $Port"
  exit 0
}

if (-not $env:PENTESTIQ_SECRET_KEY) { $env:PENTESTIQ_SECRET_KEY = New-Secret 48 }
Write-Host ""
Ok "Starting the API + web console on http://localhost:$Port"
Info "Sign in with pentestiq / p3nt3st!q (change it after first login). Ctrl-C to stop."
Write-Host ""
& $pentestiq serve --host 0.0.0.0 --port $Port
