#Requires -Version 5.1
<#
.SYNOPSIS
  PentestIQ installer for Windows — Docker SaaS stack or a local Python run.

.DESCRIPTION
  Docker path (recommended, full parity with macOS/Linux install.sh):
    powershell -ExecutionPolicy Bypass -File .\install.ps1 -Docker
    powershell -ExecutionPolicy Bypass -File .\install.ps1 -Docker -Update
    powershell -ExecutionPolicy Bypass -File .\install.ps1 -Docker -Down

  Python path (no Docker; runs the API from a virtualenv):
    powershell -ExecutionPolicy Bypass -File .\install.ps1
    powershell -ExecutionPolicy Bypass -File .\install.ps1 -Port 9090

.NOTES
  The Docker image is built from the same Debian base on every OS, so the
  scanning engine (crawler, native OWASP checks, injection fuzzer, OAST) plus
  the bundled tools (nmap, headless chromium for SPA crawl, nuclei) behave
  identically on Windows, macOS and Linux.
#>
[CmdletBinding()]
param(
  [int]$Port = 8080,
  [switch]$Docker,
  [switch]$Update,
  [switch]$Down,
  [switch]$NoServe,
  [switch]$All,
  [switch]$Help
)

$ErrorActionPreference = "Stop"
$RepoDir     = Split-Path -Parent $MyInvocation.MyCommand.Path
$ComposeFile = Join-Path $RepoDir "deploy\docker-compose.yml"
$EnvFile     = Join-Path $RepoDir "deploy\.env"

function Info($m) { Write-Host "[PentestIQ] $m" -ForegroundColor Cyan }
function Ok($m)   { Write-Host "[ ok ] $m"     -ForegroundColor Green }
function Warn($m) { Write-Host "[warn] $m"     -ForegroundColor Yellow }
function Die($m)  { Write-Host "[fail] $m"     -ForegroundColor Red; exit 1 }

if ($Help) { Get-Help $MyInvocation.MyCommand.Path -Detailed; exit 0 }

Write-Host ""
Write-Host "  PentestIQ - Windows installer" -ForegroundColor Blue
Write-Host ""

function New-Secret([int]$n = 48) {
  -join ((48..57)+(97..122) | Get-Random -Count $n | ForEach-Object {[char]$_})
}

# Resolve the compose command: v2 "docker compose" (Docker Desktop) or v1 "docker-compose".
function Get-Compose {
  try { docker compose version *> $null; if ($LASTEXITCODE -eq 0) { return @("docker","compose") } } catch {}
  if (Get-Command docker-compose -ErrorAction SilentlyContinue) { return @("docker-compose") }
  Die "Docker Compose not found. Install/enable Docker Desktop (which bundles Compose v2)."
}

function Invoke-Compose([string[]]$Rest) {
  $dc = Get-Compose
  $args = @()
  if ($dc.Count -gt 1) { $args += $dc[1] }   # the "compose" subcommand for v2
  $args += @("--env-file", $EnvFile, "-f", $ComposeFile) + $Rest
  & $dc[0] @args
}

function Write-Env {
  $dir = Split-Path -Parent $EnvFile
  if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  if (Test-Path $EnvFile) { Ok "Reusing existing secrets ($EnvFile)."; return }
  Info "Generating secrets -> $EnvFile"
  "# PentestIQ deployment secrets - generated by install.ps1. Keep private; do not commit.`n" +
  "MOBSF_API_KEY=$(New-Secret 32)`n" +
  "PENTESTIQ_SECRET_KEY=$(New-Secret 48)`n" +
  "PENTESTIQ_PORT=$Port" | Set-Content -Path $EnvFile -Encoding ASCII
  Ok "Secrets generated."
}

function Deploy-Stack {
  if (-not (Test-Path $ComposeFile)) { Die "compose file not found: $ComposeFile (run this from the PentestIQ repo)." }
  Info "Building and starting the stack (this can take a few minutes on first run)..."
  # Pre-pull the base image via the daemon, then build with the LEGACY builder.
  # BuildKit uses a separate DNS resolver that some corporate/VM DNS setups can't
  # use to reach the registry (auth.docker.io) even when the daemon resolves fine;
  # the legacy builder shares the daemon's networking. Same workaround as install.sh.
  try { docker pull python:3.11-slim *> $null } catch {}
  $env:DOCKER_BUILDKIT = "0"
  $env:COMPOSE_DOCKER_CLI_BUILD = "0"
  Invoke-Compose @("up", "-d", "--build")
  if ($LASTEXITCODE -ne 0) { Die "Build/deploy failed. See the output above." }
  Ok "Containers started."
}

function Wait-Healthy {
  Info "Waiting for the PentestIQ API to become healthy..."
  for ($i = 0; $i -lt 40; $i++) {
    try {
      $r = Invoke-WebRequest -UseBasicParsing -TimeoutSec 4 "http://localhost:$Port/health"
      if ($r.StatusCode -eq 200) { Ok "PentestIQ is up."; return }
    } catch {}
    Start-Sleep -Seconds 3
  }
  Warn "API health check timed out - it may still be starting. Check: docker compose -f `"$ComposeFile`" logs -f pentestiq"
}

function Show-Summary {
  $ip = "localhost"
  try {
    $a = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
         Where-Object { $_.IPAddress -notlike "127.*" -and $_.IPAddress -notlike "169.254.*" } |
         Select-Object -First 1
    if ($a) { $ip = $a.IPAddress }
  } catch {}
  Write-Host ""
  Write-Host "============================================================" -ForegroundColor Green
  Write-Host "  PentestIQ is deployed." -ForegroundColor Green
  Write-Host "============================================================" -ForegroundColor Green
  Write-Host "  Web console : http://localhost:$Port   (or http://$ip`:$Port)"
  Write-Host "  API docs    : http://localhost:$Port/docs"
  Write-Host "  MobSF       : http://localhost:8000  (mobile analysis engine)"
  Write-Host ""
  Write-Host "  Next steps:"
  Write-Host "    1) Open the console and sign in with pentestiq / p3nt3st!q (change the password after first login)."
  Write-Host "    2) Create a scan from New scan, or upload an app / API spec / Burp XML, then Run scan."
  Write-Host ""
  Write-Host "  Manage:"
  Write-Host "    logs   : docker compose --env-file `"$EnvFile`" -f `"$ComposeFile`" logs -f"
  Write-Host "    stop   : powershell -ExecutionPolicy Bypass -File .\install.ps1 -Docker -Down"
  Write-Host "    secrets: $EnvFile"
  Write-Host "============================================================" -ForegroundColor Green
  Write-Host ""
}

# --------------------------------------------------------------- Docker path
if ($Docker -or $Update -or $Down) {
  if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Die "Docker not found. Install Docker Desktop (https://www.docker.com/products/docker-desktop), start it, then re-run with -Docker."
  }
  try { docker info *> $null } catch { Die "Docker is installed but not running - start Docker Desktop and re-run." }

  if ($Down) {
    if (-not (Test-Path $EnvFile)) { "MOBSF_API_KEY=x`nPENTESTIQ_SECRET_KEY=x" | Set-Content -Path $EnvFile -Encoding ASCII }
    Info "Stopping the stack..."
    Invoke-Compose @("down")
    Ok "Stopped."
    exit 0
  }

  if ($Update) { Info "Update mode: rebuilding and redeploying (git pull yourself first)." }

  Write-Env
  Deploy-Stack
  Wait-Healthy
  Show-Summary
  exit 0
}

# --------------------------------------------------------------- Python path
function Test-PythonCandidate($exe, $pre) {
  $cmd = Get-Command $exe -ErrorAction SilentlyContinue
  if (-not $cmd) { return $null }
  if ($cmd.Source -and $cmd.Source -like "*\WindowsApps\*") { return $null }  # Store alias stub
  try { $out = (& $cmd.Source @pre "--version" 2>&1 | Out-String) } catch { return $null }
  if ($out -match "Python\s+(\d+)\.(\d+)") {
    $maj = [int]$Matches[1]; $min = [int]$Matches[2]
    if ($maj -gt 3 -or ($maj -eq 3 -and $min -ge 10)) {
      return [pscustomobject]@{ Exe = $cmd.Source; Pre = $pre; Ver = "$maj.$min" }
    }
  }
  return $null
}

$Py = $null
foreach ($c in @(,@("py", @("-3"))) + @(,@("python3", @())) + @(,@("python", @()))) {
  $Py = Test-PythonCandidate $c[0] $c[1]
  if ($Py) { break }
}

if (-not $Py) {
  Warn "Python 3.10+ was not found. (The 'python' Windows may offer is a Microsoft Store placeholder.)"
  if (Get-Command winget -ErrorAction SilentlyContinue) {
    Info "Installing Python 3.12 via winget..."
    try {
      winget install --id Python.Python.3.12 -e --source winget --accept-package-agreements --accept-source-agreements
      Write-Host ""
      Warn "Python installed. Close this window, open a NEW PowerShell, and run install.ps1 again."
      exit 0
    } catch {
      Die "Automatic install failed. Get Python 3.10+ from https://python.org (tick 'Add python.exe to PATH'), then re-run."
    }
  }
  Die "Install Python 3.10+ from https://python.org (tick 'Add python.exe to PATH') and re-run, or use -Docker with Docker Desktop."
}
Ok "Python $($Py.Ver) detected."

$venv = Join-Path $RepoDir ".venv"
if (-not (Test-Path $venv)) {
  Info "Creating virtual environment (.venv)..."
  & $Py.Exe @($Py.Pre) -m venv "$venv"
}
$vpy = Join-Path $venv "Scripts\python.exe"
if (-not (Test-Path $vpy)) { Die "venv creation failed (no $vpy)." }

Info "Installing PentestIQ and dependencies (this may take a minute)..."
& $vpy -m pip install --upgrade pip --quiet
$extras = if ($All) { ".[all]" } else { ".[api,reports]" }
& $vpy -m pip install --quiet $extras
Ok "PentestIQ installed."

$pentestiq = Join-Path $venv "Scripts\pentestiq.exe"
& $pentestiq version

if ($NoServe) {
  Write-Host ""
  Info "Skipping server start (-NoServe). To run later:  `"$pentestiq`" serve --host 0.0.0.0 --port $Port"
  exit 0
}

if (-not $env:PENTESTIQ_SECRET_KEY) { $env:PENTESTIQ_SECRET_KEY = New-Secret 48 }
Write-Host ""
Ok "Starting the API + web console on http://localhost:$Port"
Info "Sign in with pentestiq / p3nt3st!q (change it after first login). Ctrl-C to stop."
Write-Host ""
& $pentestiq serve --host 0.0.0.0 --port $Port
