"""C1t — SCA + SBOM: lockfile parsing, OSV mapping, CycloneDX, and the scan API."""
from __future__ import annotations

import json

import pytest
from fastapi.testclient import TestClient

from pentestiq.sca import (parse_components, parse_package_lock, parse_requirements,
                           parse_yarn_lock, scan_dependencies, OSVClient, build_sbom)
from pentestiq.sca.parsers import Component
from pentestiq.models import Severity, AssetType
from pentestiq.api.app import create_app
from pentestiq.config import AppConfig
from pentestiq.storage import SqliteEngagementStore, SqliteAuthStore
from pentestiq.auth.service import AuthService


# ---- parsers ------------------------------------------------------------
PKG_LOCK_V3 = json.dumps({"name": "app", "lockfileVersion": 3, "packages": {
    "": {"name": "app"},
    "node_modules/lodash": {"name": "lodash", "version": "4.17.15"},
    "node_modules/log4js": {"version": "6.3.0"},
    "node_modules/@scope/util": {"name": "@scope/util", "version": "1.0.0", "dev": True},
}})
PKG_LOCK_V1 = json.dumps({"name": "app", "lockfileVersion": 1, "dependencies": {
    "minimist": {"version": "1.2.0"},
    "mkdirp": {"version": "0.5.1", "dependencies": {"minimist": {"version": "0.0.8"}}},
}})
REQS = "Django==3.2.0\nrequests==2.25.1  # pinned\nflask>=1.0\n-r other.txt\n# comment\nPyYAML[extra]==5.3.1"
YARN = '''# THIS IS AN AUTOGENERATED FILE
lodash@^4.17.0:
  version "4.17.15"
  resolved "https://registry.yarnpkg.com/lodash"
"@babel/core@^7.0.0", "@babel/core@^7.1.0":
  version "7.12.3"
'''


def test_parse_package_lock_v3():
    comps = parse_package_lock(PKG_LOCK_V3)
    names = {c.name: c for c in comps}
    assert names["lodash"].version == "4.17.15"
    assert names["log4js"].version == "6.3.0"
    assert names["@scope/util"].scope == "optional"
    assert names["@scope/util"].purl == "pkg:npm/%40scope/util@1.0.0"
    assert names["lodash"].ecosystem == "npm"


def test_parse_package_lock_v1_nested():
    comps = parse_package_lock(PKG_LOCK_V1)
    keys = {c.key for c in comps}
    assert "npm:minimist@1.2.0" in keys and "npm:minimist@0.0.8" in keys
    assert "npm:mkdirp@0.5.1" in keys


def test_parse_requirements_pins_only():
    comps = parse_requirements(REQS)
    got = {c.name: c.version for c in comps}
    assert got == {"Django": "3.2.0", "requests": "2.25.1", "PyYAML": "5.3.1"}
    assert all(c.ecosystem == "PyPI" for c in comps)


def test_parse_yarn_lock_multi_spec():
    comps = parse_yarn_lock(YARN)
    got = {c.name: c.version for c in comps}
    assert got["lodash"] == "4.17.15" and got["@babel/core"] == "7.12.3"


def test_detect_by_filename_and_content():
    assert [c.name for c in parse_components(REQS, "requirements.txt")]
    assert [c.name for c in parse_components(PKG_LOCK_V3, "package-lock.json")]
    # content-only detection (unknown filename)
    assert [c.name for c in parse_components(PKG_LOCK_V3, "deps.json")]


# ---- OSV mapping (fake transport) --------------------------------------
_VULNDB = {"GHSA-x": {
    "id": "GHSA-x", "aliases": ["CVE-2020-8203"],
    "summary": "Prototype pollution in lodash",
    "database_specific": {"severity": "HIGH"},
    "severity": [{"type": "CVSS_V3", "score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:H/A:N"}],
    "affected": [{"package": {"name": "lodash", "ecosystem": "npm"},
                  "ranges": [{"type": "SEMVER", "events": [{"introduced": "0"}, {"fixed": "4.17.19"}]}]}],
    "references": [{"type": "ADVISORY", "url": "https://github.com/advisories/GHSA-x"}]}}


def _fake_fetch(url, payload=None):
    if url.endswith("/querybatch"):
        out = []
        for q in payload["queries"]:
            out.append({"vulns": [{"id": "GHSA-x"}]} if q["package"]["name"] == "lodash" else {})
        return {"results": out}
    return _VULNDB.get(url.rsplit("/", 1)[-1], {})


def test_osv_client_maps_vuln():
    comps = parse_package_lock(PKG_LOCK_V3)
    vulns = OSVClient(fetch=_fake_fetch).scan(comps)
    assert len(vulns) == 1
    v = vulns[0]
    assert v.component.name == "lodash" and v.cves == ["CVE-2020-8203"]
    assert v.severity == "high" and v.fixed_version == "4.17.19"
    assert v.cvss_vector and v.cvss_vector.startswith("CVSS:3.1")


def test_osv_offline_returns_no_vulns():
    comps = parse_requirements(REQS)
    assert OSVClient(offline=True).scan(comps) == []


# ---- scanner: findings + SBOM ------------------------------------------
def test_scan_dependencies_findings_and_sbom():
    res = scan_dependencies(PKG_LOCK_V3, filename="package-lock.json",
                            subject="myapp", osv=OSVClient(fetch=_fake_fetch))
    assert res.component_count == 3 and res.vulnerable_count == 1
    f = res.findings[0]
    assert f.category == "A06:2021" and f.severity is Severity.HIGH
    assert f.asset.type is AssetType.CODEBASE and f.location == "lodash@4.17.15"
    assert "CVE-2020-8203" in f.references
    assert "4.17.19" in f.remediation
    # CycloneDX SBOM
    assert res.sbom["bomFormat"] == "CycloneDX" and res.sbom["specVersion"] == "1.5"
    assert len(res.sbom["components"]) == 3
    assert res.sbom["serialNumber"].startswith("urn:uuid:")
    assert len(res.sbom["vulnerabilities"]) == 1
    assert res.sbom["vulnerabilities"][0]["affects"][0]["ref"] == "pkg:npm/lodash@4.17.15"


def test_scan_offline_still_produces_sbom():
    res = scan_dependencies(REQS, filename="requirements.txt", offline=True)
    assert res.component_count == 3 and res.vulns == [] and res.findings == []
    assert res.sbom["specVersion"] == "1.5" and len(res.sbom["components"]) == 3


def test_sbom_without_vulns_has_no_vuln_key():
    comps = parse_requirements(REQS)
    doc = build_sbom(comps, subject="x")
    assert "vulnerabilities" not in doc and len(doc["components"]) == 3


# ---- API: upload SCA + SBOM download -----------------------------------
@pytest.fixture
def ctx(tmp_path, monkeypatch):
    monkeypatch.setenv("PENTESTIQ_INTEL_OFFLINE", "1")   # no network in the API scan
    db = str(tmp_path / "pentestiq.db")
    store = SqliteEngagementStore(db)
    auth = AuthService(SqliteAuthStore(db), secret_key="s", session_ttl=3600)
    app = create_app(store=store, auth=auth, config=AppConfig(data_dir=str(tmp_path)))
    c = TestClient(app)
    tok = c.post("/auth/login", json={"username": "pentestiq", "password": "p3nt3st!q"}).json()["token"]
    return c, {"Authorization": "Bearer " + tok}


def test_api_codebase_upload_and_sbom(ctx):
    c, H = ctx
    r = c.post("/engagements/upload", headers=H,
               data={"asset_type": "codebase", "name": "web-app deps"},
               files={"file": ("package-lock.json", PKG_LOCK_V3, "application/json")})
    assert r.status_code == 201
    eid = r.json()["id"]
    det = c.get(f"/engagements/{eid}", headers=H).json()
    a0 = det["engagement"]["assets"][0]
    assert a0["type"] == "codebase" and a0["metadata"]["component_count"] == 3
    # inventory registered the codebase asset
    assert any(x["identifier"] == "web-app deps" for x in c.get("/assets", headers=H).json())
    # SBOM download
    s = c.get(f"/engagements/{eid}/sbom", headers=H)
    assert s.status_code == 200
    assert s.headers["content-type"].startswith("application/vnd.cyclonedx+json")
    assert s.json()["bomFormat"] == "CycloneDX" and len(s.json()["components"]) == 3


def test_api_codebase_rejects_unparseable(ctx):
    c, H = ctx
    r = c.post("/engagements/upload", headers=H, data={"asset_type": "codebase"},
               files={"file": ("notes.txt", b"just some text, no deps", "text/plain")})
    assert r.status_code == 422


def test_api_sbom_404_for_non_sca(ctx):
    c, H = ctx
    eid = c.post("/engagements", headers=H, json={"engagement": {"name": "web"},
                 "scope": {"in_scope": []}}).json()["id"]
    assert c.get(f"/engagements/{eid}/sbom", headers=H).status_code == 404
